### ISSUE TITLE
seekBar.calculateDistance(event) doesn't work in newer version of VideoJS (4.5)

### ISSUE THREAD

**Issue by tim-peterson** [mickey/videojs-progressTips#2]
getting the following error on this line with videojs 4.5:

```
seekBar = player.controlBar.progressControl.seekBar;
 timeInSeconds = seekBar.calculateDistance(event) * seekBar.player_.duration();
```

`Uncaught TypeError: undefined is not a function`

`undefined` refers to `seekBar`

**Comment by adamtal3** [comment]
The undefined was reffering to calculateDistance.

I've fixed the plugin to work with videojs 4.6.4:
https://github.com/adamtal3/videojs-progressTips

It does has an issue though when using the video.js and not video.dev.js because the minification changed the name of "techName".

**Comment by mickey** [comment]
It should work with the last version, see the last [PR](https://github.com/mickey/videojs-progressTips/pull/3) for details.
